###
POST http://127.0.0.1:8000/cats/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODMyMzEwLCJpYXQiOjE3Njg3NDU5MTAsImp0aSI6IjZmZjFkZjE3MjgxYjRkZTA4ODg2MGE2ODU0M2YyNjhhIiwidXNlcl9pZCI6MX0.efYDlGtRDeObC7-WB1bxNqtfCl1t7y0sNIdrSeWP994

{
    "name": "oldcat",
    "color": "White",
    "birth_year": 1989,
    "owner": 1,
    "achievements": [
        {"achievement_name": "поймал мышку"}
    ]
    
}

###
GET http://127.0.0.1:8000/cats/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODMyMzEwLCJpYXQiOjE3Njg3NDU5MTAsImp0aSI6IjZmZjFkZjE3MjgxYjRkZTA4ODg2MGE2ODU0M2YyNjhhIiwidXNlcl9pZCI6MX0.efYDlGtRDeObC7-WB1bxNqtfCl1t7y0sNIdrSeWP994
###
GET http://127.0.0.1:8000/cats/recent-white-cats/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODMyMzEwLCJpYXQiOjE3Njg3NDU5MTAsImp0aSI6IjZmZjFkZjE3MjgxYjRkZTA4ODg2MGE2ODU0M2YyNjhhIiwidXNlcl9pZCI6MX0.efYDlGtRDeObC7-WB1bxNqtfCl1t7y0sNIdrSeWP994

###
GET http://127.0.0.1:8000/mycats/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODMyMzEwLCJpYXQiOjE3Njg3NDU5MTAsImp0aSI6IjZmZjFkZjE3MjgxYjRkZTA4ODg2MGE2ODU0M2YyNjhhIiwidXNlcl9pZCI6MX0.efYDlGtRDeObC7-WB1bxNqtfCl1t7y0sNIdrSeWP994

###
GET http://127.0.0.1:8000/cats
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODMyMzEwLCJpYXQiOjE3Njg3NDU5MTAsImp0aSI6IjZmZjFkZjE3MjgxYjRkZTA4ODg2MGE2ODU0M2YyNjhhIiwidXNlcl9pZCI6MX0.efYDlGtRDeObC7-WB1bxNqtfCl1t7y0sNIdrSeWP994



###
PATCH http://127.0.0.1:8000/cats/1/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODMyMzEwLCJpYXQiOjE3Njg3NDU5MTAsImp0aSI6IjZmZjFkZjE3MjgxYjRkZTA4ODg2MGE2ODU0M2YyNjhhIiwidXNlcl9pZCI6MX0.efYDlGtRDeObC7-WB1bxNqtfCl1t7y0sNIdrSeWP994

{
    "name": "blackcat1",
    "color": "#228B22",
    "birth_year": 2009
}

### 
POST http://127.0.0.1:8000/cats/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODMyMzEwLCJpYXQiOjE3Njg3NDU5MTAsImp0aSI6IjZmZjFkZjE3MjgxYjRkZTA4ODg2MGE2ODU0M2YyNjhhIiwidXNlcl9pZCI6MX0.efYDlGtRDeObC7-WB1bxNqtfCl1t7y0sNIdrSeWP994


{
    "name": "Барсик",
    "color": "White",
    "birth_year": 2017,
    "owner": 1,
    "achievements": [
        {"achievement_name": "поймал мышку"},
        {"achievement_name": "разбил вазу"}
    ]
} 



### 
POST http://127.0.0.1:8000/api-token-auth/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODMyMzEwLCJpYXQiOjE3Njg3NDU5MTAsImp0aSI6IjZmZjFkZjE3MjgxYjRkZTA4ODg2MGE2ODU0M2YyNjhhIiwidXNlcl9pZCI6MX0.efYDlGtRDeObC7-WB1bxNqtfCl1t7y0sNIdrSeWP994

{
    "username": "idotsenko",
    "password": "korgAX3GHSPA"
}

### 
POST http://127.0.0.1:8000/auth/users/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODMyMzEwLCJpYXQiOjE3Njg3NDU5MTAsImp0aSI6IjZmZjFkZjE3MjgxYjRkZTA4ODg2MGE2ODU0M2YyNjhhIiwidXNlcl9pZCI6MX0.efYDlGtRDeObC7-WB1bxNqtfCl1t7y0sNIdrSeWP994

{
    "username": "test",
    "password": "testtest1234"
}
### 
POST http://127.0.0.1:8000/auth/jwt/create/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODMyMzEwLCJpYXQiOjE3Njg3NDU5MTAsImp0aSI6IjZmZjFkZjE3MjgxYjRkZTA4ODg2MGE2ODU0M2YyNjhhIiwidXNlcl9pZCI6MX0.efYDlGtRDeObC7-WB1bxNqtfCl1t7y0sNIdrSeWP994

{
    "username": "test",
    "password": "testtest1234"
}

# {
#   "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2ODgzMjMxMCwiaWF0IjoxNzY4NzQ1OTEwLCJqdGkiOiJiYTU1OWFlY2RhYzI0NDY5YWY3NDQzZTk5NjEzMTI4YSIsInVzZXJfaWQiOjF9.0U1DWL7xld7SlwUEV_EJKs43tNmR3_ZW5XCrg04dz5I",
#   "access": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4ODMyMzEwLCJpYXQiOjE3Njg3NDU5MTAsImp0aSI6IjZmZjFkZjE3MjgxYjRkZTA4ODg2MGE2ODU0M2YyNjhhIiwidXNlcl9pZCI6MX0.efYDlGtRDeObC7-WB1bxNqtfCl1t7y0sNIdrSeWP994"
# }